# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=35)),
                ('CountryCode', models.CharField(max_length=3)),
                ('District', models.CharField(max_length=20)),
                ('Population', models.IntegerField()),
            ],
        ),
    ]
